name: qr_app
description: QR + Logo Real Aura Engine
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ^3.0.1
  image_picker: ^1.0.4 
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.1
  share_plus: ^7.1.0
  permission_handler: ^11.0.1
  palette_generator: 0.3.3+3
  image: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png