name: qr_app_comagro
description: App nativa generadora de QRs V53 para Comagro
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0        
  image_picker: ^1.0.4 
  path_provider: ^2.1.1

flutter:
  uses-material-design: true
