name: qr_app
description: QR + Logo Real Aura Engine
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ^3.0.1
  image_picker: ^1.0.4 
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  palette_generator: 0.3.3+3
  image: ^4.1.3
  share_plus: ^7.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
