name: qr_app
description: Aplicacion QR + Logo Nativo
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0        # Genera la matriz del QR
  image_picker: ^1.0.4 
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.1
  share_plus: ^7.1.0
  path_provider: ^2.1.1
  image: ^4.1.3             # Para procesar el logo internamente

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
