name: qr_app
description: Aplicacion QR + Logo
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0        
  image_picker: ^1.0.4 
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
